### ISSUE TITLE
Onboard to-the-sun

### ISSUE THREAD

**Issue by DanielWarfield1** [DanielWarfield1/nClusterFramework#2]
So, GitHub has a kanban style project management workflow which is broken up into projects. The core element of this system is an "issue", which this is.

It has an Assignee (you) labels (documentation and help wanted), it's associated with a project, etc.

We don't have to get too crazy, I think the real power here is that we can split up out conversation into specific issues, rather than have one massive message board that's difficult to keep up with. We can still be conversational on discord, (you cant @ me on discord to get my attention, for instance), but talking about specific issues on here might keep us more in check.

Once tasks are done they get moved around in their specific project (if one is associated). For example:
https://github.com/DanielWarfield1/nClusterFramework/projects/1

**Comment by to-the-sun** [comment]
Sounds good. Yeah, I've very briefly used the issues on Github before. So should I just close the issue and call that my official on-boarding?

**Comment by DanielWarfield1** [comment]
@to-the-sun You don't have to worry about managing projects, it's mostly for whoever is developing (me). For this one I suppose it would make sense, but I'll move it over while I'm here
